ERROR:wandb.sdk.internal.internal_api:404 response executing GraphQL.
ERROR:wandb.sdk.internal.internal_api:{"errors":[{"message":"could not find sweep cnn-pelsvae/train-classsifier/exp_s_10000_l_50_sn_2 during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
